# Generated by Django 3.1.1 on 2020-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='article_tag',
            options={'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '站点'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name_plural': '调整顺序'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='article_tag',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='article_tag',
            name='down_num',
        ),
        migrations.RemoveField(
            model_name='article_tag',
            name='up_num',
        ),
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_num',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='article',
            name='up_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
